### ISSUE TITLE
Configuration instructions

### ISSUE THREAD

**Issue by sdras** [tholman/what-have-you-made-today#1]
Hey Tim! 
This is so great! I added it to firefox but- are there any instructions on how to configure it?

Thanks for making it!
Sarah

**Comment by tholman** [comment]
Ahh, there's a button on the bottom right! Sounds like I've gotta make it bolder!

**Comment by tholman** [comment]
@sdras ~ Added some small instructions (about where to find the button) to the readme, but will do a little design rejigger tomorrow when I wake up  :)

**Comment by sdras** [comment]
Oh! I didn't see that. But even when it pops up, I can't seem to type anything? Lol sorry if I'm being obtuse
<img width="248" alt="screen shot 2017-12-11 at 9 23 29 am" src="https://user-images.githubusercontent.com/2281088/33841509-2c5ffce6-de55-11e7-9873-1fc371b28d15.png">

**Comment by sdras** [comment]
Sounds good!

**Comment by tholman** [comment]
Oh... this is strange. I guess firefox's extension api is returning no top sites, so its not populated.

**Comment by tholman** [comment]
... which means 0 sites are probably saved in now too. Definitely a bug.

**Comment by stephmarx** [comment]
I'm getting the same problem on Firefox.

**Comment by tholman** [comment]
@sdras @stephmarx Sent through a small update on FireFox... any luck if you update?

**Comment by gluons** [comment]
I got the same problem. I just fresh install 1.0.3.

**Comment by tholman** [comment]
:(

Trying to debug it, its a confusing one... no errors in the console? Its like something is stopping any data from coming thought during init.

**Comment by gluons** [comment]
I see error in console.

![screenshot at 2017-12-12 00-37-29](https://user-images.githubusercontent.com/4688092/33845018-aa789500-ded4-11e7-8063-5294a1a08733.png)

**Comment by tholman** [comment]
Ahhh, empty data field. This I can fix.

**Comment by stefanivic** [comment]
@tholman amazing work on it. Thank you for creating this.

I was checking your code on Github. Firefox has a very similar API to chrome regarding getting top sites.
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/topSites/get Have you checked this out ?

**Comment by tholman** [comment]
@gluons @sdras @stephmarx - 1.0.5 is out on FireFiox now, 99% sure its going to fix this.

Problem was an empty data field, classic!

**Comment by stefanivic** [comment]
@tholman it is working now.

**Comment by tholman** [comment]
🙏

**Comment by stephmarx** [comment]
Working for me too now, thanks!

**Comment by gluons** [comment]
It works for me too. 🎉 

![screenshot at 2017-12-12 20-25-44](https://user-images.githubusercontent.com/4688092/33886923-a755f240-df7a-11e7-8b36-b806a166ca43.png)

**Comment by sdras** [comment]
Yay it's fixed for me too!
